use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DataType {
    SmallInt,
    Integer,
    BigInt,
    Float,
    Double,
    Decimal { precision: Option<u32>, scale: Option<u32> },
    Serial,
    BigSerial,
    Boolean,
    Char(Option<u32>),
    Varchar(Option<u32>),
    Text,
    Blob,
    Bytea,
    Date,
    Time,
    TimeTz,
    Timestamp,
    TimestampTz,
    Interval,
    Json,
    Jsonb,
    Uuid,
    Inet,
    Cidr,
    MacAddr,
    Point,
    Line,
    Box,
    Circle,
    Array(Box<DataType>),
    Enum { name: String, values: Vec<String> },
    Unknown(String),
}
